#rds 발급 후 수정해야함
version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    networks:
      - myapp-network
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: myapp
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - myapp-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/your_database
      SPRING_DATASOURCE_USERNAME: your_user
      SPRING_DATASOURCE_PASSWORD: your_db_password
    volumes:
      - .:/app

networks:
  myapp-network:
    driver: bridge

volumes:
  db_data:
