server:
  port: 8080

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  redirect-uri: ${SPOTIFY_REDIRECT_URI}
  scope: user-read-private user-read-email
  authorization-uri: https://accounts.spotify.com/authorize
  token-uri: https://accounts.spotify.com/api/token
  user-info-uri: https://api.spotify.com/v1/me
